---

kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: homa
  labels:
    app: mariadb
    kubernetes.io/name: mariadb
spec:
#  type: ClusterIP
  type: LoadBalancer
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
