---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-volume
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
