---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: switcher-webapi
  namespace: switcher
  labels:
    app: switcher-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: switcher-webapi
  template:
    metadata:
      labels:
        app: switcher-webapi
    spec:
      containers:
        - name: switcher-webapi
          image: 'avishayil/switcher_webapi:latest'
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: CONF_DEVICE_IP_ADDR
              value: 10.0.0.6
            - name: CONF_THROTTLE
              value: '1.0'
          envFrom:
            - secretRef:
                name: switcher-webapi
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
