---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-volume
          nfs:
            server: 10.0.0.29
            path: /export/kube-storage/influxdb
      containers:
        - name: influxdb
          image: 'influxdb:latest'
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
