---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-volume
          nfs:
            server: 10.0.0.29
            path: /export/kube-storage/grafana
      containers:
        - name: grafana
          image: 'grafana/grafana:latest'
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
