---

kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    kubernetes.io/name: grafana
spec:
  ports:
    - name: grafana-http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31272
  selector:
    app: grafana
  type: NodePort
