---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  template:
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
  encryptedData:
    Z2MA_SETTINGS__MQTTPASSWORD: AgAgZh9WD4QMtTk3s/4hqSAPSO6u6KM9sIWeZAwfHiqntXq3iKMEWxUATuLvdHeARmFH2zwFyyATKYi8BNwGWQm37dRg5B/DRwkisxieqfyO/kE54JBMh1k7F4ayctLvhYQZaMSVQUW/iZz+Xnd/HvmYHE4osO70ZNFFqHCrodZADfvTie+At8gLSIR5Gizsk2kvJWAWe5Pi27ml2FzVa7r4hk+r74joKWnmILHnVTbL7u9nx9KayYE6dDMp3sDDmr0U9VDUgeXJTNLlMhSzvvOYUo2oKjMDvJ29gpkuccAo3S/b2178auxhoQoDVCaRsAnXlEqd6cvFWyOFtyEwFro7h1tu2P39y7oTlg1X4xr8e/SR+3Qpffxo7yyyXPhHcDHNNQb6T8nrGSD7/7BIswHWlIMwJRXtRoO/IvIuK0GaxGR2eT4Ev+YNofQstzehU1AYIwm6+V5fYWDJeQMluKtrBYCcykM6XsXz4tApE8GGjLlcwEkHwOY8aoafbhxagSdwoPEUo69ou/mFpRD3tQQMwYbqktt6f9HwwPcsDBsxm0IYuv4pwKlRpvMP4d5z2m2FMcLi7+ouIqdFk8cRlPkbKr0Ai3xWJeFwMo5/CkUOsLanIM66NySGnao+QwZgecCY1EGIKbCFPbta5PpijGgXPHHvr7B11aPCh/bcdZPyz+ygToKZg82RdAuDA1rb2FWByGHDSc03mrkFD2Pi1BrU
    Z2MA_SETTINGS__MQTTUSERNAME: AgBFZrDk8pnRoyrzz7GUujT1smxH43dIjR3pmjbXz7bTwt5f0AZQXeDkuHJ1kfFTHspfQU2PJ/ij2AgtbCzhpDinBBBV1+XmhJVkyJyRXZA1UdAal6VpKHzfbEWaD5ZcV3Fu5MWgJ+tsUkvJaDYxcyy6x0Gs75bsDS/ElNyvemkLXNdyDqIcNhqmur0uAYVqnkCG3Z55z2KXu1dTnbV2ghF67+unYlerW5Grb8w3cjg7K97tK2C1HU5g1+YRiXbCmr0BqDf8N/jyqFc48RLnWPVXTsWH+A1Uk39O24RP+/L0k1m3zWpm1C3prQzgZqG0sGj+URtqmpap3/I7qsmG4I4NHi1rDIDxzPiv74UNajV6s2nSBA9BOD0k6bR6RQL+lXhcCIeKiq2zZSuK9lMwU7Xxofu5G3hGEvQJzGrLvQcNa1UBuS+4cRCoUaEyHMhmIuHYDw/Fho+DqDzt18hZ4jI44EJOSOWdi1b/NttWACtFhxVnhqZDLB3vZrRw+1tFsvzZX5ncutiQZjcE2mnNQ0/RqQgFuFos/w2Uue8e07Zf6fQqOVJa2ffHNAEGaTZ6m54LemkgOHtLJevropDmfPx/wQPVa70QaY54X3FQ+BtNmIpyYAxVBtQ77xPFJgPqsMz4O88mOyHO17oZaJ1eEBqxHpnGYIpkXdH8Ftls4sEb+SNAZU80Civi9o6RrOK992XDwjrVyAnTCBnykxWF1A==
