---

kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
  creationTimestamp:
spec:
  template:
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
      creationTimestamp:
  encryptedData:
    appsettings.json: AgCE0fmWpBpRsCyDfRsRaAoxoFvXlh24BpP97nkV1VQVxWyDcTYw8LYWVilQonkDgpONgiE0zEKdi4+bDGpr3mT/+sntGQ/1EAHVzcJzG7Y2vPpFRyy6vBKMPrqYifmU7FI/JCz+cEksh3rsGqEjk79Gm2TEsL19dgaHPsD2F5AWXoy0scFva1+Q3MZzpP8HY/FpS+gdo8ZXwts9kGUpvmOZnr52B9ymQKg/CIXqB9YGLd5TadUd3zjc+wlBEnoSJgHU8d3oeMMgCe5Hy1N8psF6UO8m1eokJ//BmNPiSX7wIsevZSDsnUvZ5o1flR0O/lbcL+CRXyHGPGx7KxPoNlRqpWN8x5IY0Y4XuEKDMBtS+9WWDHozcyr+n8u6bJnYYmZIwZH2/8U2ecImzRUfqg0RLMMvRUkRQCQF7c9xn/IT3awop7r2Ep5TIN1Gm8xLk6WD5D9pA5JrVIv0h9COJMRKUkgU1KwlIlxs1mmIk05RifsCJcufcFkXynIUlnEx9iQdrdhZrzg8+GEdaHVW0NNOZZS30WGD+4QHXMOTrZq+WyKL/KFgjCqbzH+yfr1mpD4a6LrC3bObGH+9mcI0rZFnN0MeunYBS8k5aaojoGfijVPnN8Ca+ELfwfTjRXldynv0yOECeTK1l4e87L1IGf7CSYG+7LZmLlbL6U+TKQaK8bHwMdF4QrzoTWvbhrTYLpUNyeDBVk1jXgFzlEc0yCOYTg4FvWJIwhCaQhsBNFoS/kezOF75KhIPwJo2EMChwwBQXZsEDoLM37GwLRSxVi9/j3tFExKo46f5TFF1A/rkMJx5SwbOQyzcaY5SJ95NfMMrBYsW8jmZAr0kfnXlK8VSL7gekl6NP6IPUNJWRHJl1Fv7tn6FJQQzcRNETxnekS5NX4mO2aBF2cxn/8pcsHQsHCy6SSj/u+RSVgARnVfwdXefxlu8YJxdg/VtGynZmW68ZOLfCifhcvQYqxox3xsmOB2WKoZtZaEwNiiRQ6wg48xQDEGFdPSaqu9vyywMPG6mGlVfGjTN7hc=
