---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: zigbee2mqttassistant
  namespace: zigbee2mqtt
  labels:
    app: zigbee2mqttassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqttassistant
  template:
    metadata:
      labels:
        app: zigbee2mqttassistant
    spec:
      containers:
        - name: zigbee2mqttassistant
          image: 'carldebilly/zigbee2mqttassistant'
          envFrom:
            - secretRef:
                name: zigbee2mqtt
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
