---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-udp
  namespace: infrastructure
spec:
  ports:
  - port: 514
    protocol: UDP
    targetPort: 514
  selector:
    app: rsyslog
#  externalTrafficPolicy: Local
#  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-tcp
  namespace: infrastructure
spec:
  ports:
  - port: 514
    protocol: TCP
    targetPort: 514
  selector:
    app: rsyslog
#  externalTrafficPolicy: Local
#  sessionAffinity: None
  type: LoadBalancer
