---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-tcp
  namespace: infrastructure
spec:
  ports:
  - port: 514
    targetPort: 514
  selector:
    app: rsyslog
  externalTrafficPolicy: Local
  sessionAffinity: None
  type: LoadBalancer
