---
# NEXTCLOUD APP
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud-app
  namespace: cloud
  labels:
    app: nextcloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-app
  template:
    metadata:
      labels:
        app: nextcloud-app
    spec:
      volumes:
        - name: nextcloud-volume
          hostPath:
            path: /storage/bluepool/nextcloud
      containers:
        - name: nextcloud-cron
          image: 'nextcloud:apache'
          command: ["/cron.sh"]
          volumeMounts:
          - name: nextcloud-volume
            mountPath: /var/www/html
        - name: nextcloud-app
          image: 'nextcloud:apache'
          volumeMounts:
          - name: nextcloud-volume
            mountPath: /var/www/html
          ports:
          - containerPort: 80
          env:
          - name: NEXTCLOUD_TRUSTED_DOMAINS
            valueFrom:
              configMapKeyRef:
                name: nextcloud-config
                key: trusteddomains
          - name: NEXTCLOUD_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: admin.user
          - name: NEXTCLOUD_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: admin.password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: nextcloud-config
                key: postgres.host
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: nextcloud-config
                key: postgres.db
          - name: POSTGRES_USER
            valueFrom:
             secretKeyRef:
               name: nextcloud.nextcloud-cluster.credentials.postgresql.acid.zalan.do
               key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
             secretKeyRef:
               name: nextcloud.nextcloud-cluster.credentials.postgresql.acid.zalan.do
               key: password
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: nextcloud-config
                key: redis.host
          - name: REDIS_HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: nextcloud-config
                key: redis.port
          - name: REDIS_HOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: redis.password
      restartPolicy: Always
      nodeName: hcis1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
