---

kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  template:
    metadata:
      name: mosquitto
      namespace: mosquitto
  encryptedData:
    passwordfile: AgBtVB70sI/nd+wgUugAXlpFuLugFnh5H1Uh2WU4Pigul8joyxpGOwHiYfb+6RA1oY9fKu89U3W0Ber7RSZPi4Bfo3wW1oUEKx5+l3ZuIfpds9QJA8KzLWk+Yz1v6H/gUsFjQMdNqM+G5i3y4mgeJGwiA8xtoZa5jv6uCcmc5KIOu5TxouGq49c+BOfk6jEDCiPu28k9dpkq272eLf5Ee1P4z6c5J5+uT2NfZvtt5YjHxRMCJI2PqM5wPKSeGv85FPQO9ihAHD+d4GCYxHrLaqL8RWJUBVO/1cEdqmiCleEEA/2cznYtRx1PoAaNEPzamwiZ3XUIb5iv58E55E153mxkmq2/M6u/Da6VtZ0LcMDFl/vKqCMKHf93EkEzGYQEwRjT0JCM4fdnBSMdxJlG33XpiDGA2zMs4+D4BMPbXxCxIia4w2v9N6l7sZKnaim3h208ZqK8mg+Lg/1IdFNeiyLVRgNC1EvDANNvQw8/1INzf4mpkmX1pB6Mma91drGF+wV4fM8ulYt5FTWqz+KYTBGg4zrXrSjrNGmM/Wsd6chtJXbIEo281wD5lNDdRbzq2HeSX6QKPRypnOrWfq3ZL2d2kmx95xbj9x8UGBSSFh4erKqMC27JUFfFK1+oqO7a7z29kM8+WJLlb3oLHqTTHb2BnO9CXP2aNhbHFdcJasQmGacupn8oJSr7u/vkK6JtLbx/ljh/xEOS7hFiuulJMSC7JsKv+19Qy/+fGXo74X7s20JhxMc/7hops5nMV6DuBvqXxSECT3itAg891EnqcvKyy9QRjxS5F1s2g6EXLBjLa6Ol8uymBqNg687Qz77G12MuJKgvj/tCHXI12TkY/triFYw3XnPSsIT2ULs=
