apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  namespace: homa
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      volumes: 
      - name: storage
        hostPath:
          path: /data/homa/node-red
      - name: node-red-pv-storage
        persistentVolumeClaim:
          claimName: node-red-pvc # 绑定pvc.yml下metadata.name
      initContainers:
        - name: rsync-down
          image: 'ogivuk/rsync'
          command: ["./rsync.sh"]
          args: ["-a","-v","--progress","/data/src/", "/data/dst/"]
      #    command: ["/bin/echo bonjour"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: node-red-pv-storage
            mountPath: /data/src
          - name: storage
            mountPath: /data/dst
      containers:
      - name: "node-red"
        image: nodered/node-red
        imagePullPolicy: IfNotPresent
        env:
          - name: PORT
            value: "1880"
        volumeMounts: # 对spec.volumes下声明的volumes配置具体的挂载
        - name: "storage" # 使用上面spec.volumes中的node-red-pv-storage
          mountPath: "/data"
        - name: node-red-pv-storage
          mountPath: /backup
#        resources:
#          limits:
#            cpu: 1024m
#            memory: 1Gi
#          requests:
#            cpu: 1024m
#            memory: 1Gi
      nodeName: vps-e750b1ad 