---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpimx-tunnel
  namespace: infrastructure
  labels:
    app: rpimx-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpimx-tunnel
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rpimx-tunnel
    spec:
      containers:
        - name: rpimx-tunnel
          image: 'mebaxyz/openssh-server'
          env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "0"
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-public-key
                key: mebarpimx
          ports:
            - containerPort: 2222
              protocol: TCP
            - containerPort: 22
              protocol: TCP
            - containerPort: 22222
              protocol: TCP
          #resources:
          #  limits:
          #    cpu: 100m
          #    memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      nodeSelector:
        #zone: datacenter
        #wg-node: central
        kubernetes.io/hostname: vps-e750b1ad
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
