apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh:secret-reader
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: test-cert-manager
    app.kubernetes.io/tier: backend
    app.kubernetes.io/managed-by: Ops
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-ovh:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-ovh:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-ovh
