apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-ne00-roche
  namespace: logos
spec:
  secretName: tls-ne00-roche
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - ne00.roche.meba.xyz
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
