---
#couchdb Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data-claim
  namespace: dev
spec:
  storageClassName: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi      

---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: couchdb
  namespace: dev
spec: 
  
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata: 
      labels:
        app: couchdb
       
    spec: 
      containers:
        #couchdb          
      - name: couchdb
        image: registry.dev.meba.xyz/couchdb:v1.0.0
        ports:
        - containerPort: 5984
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: couchdb-data
      imagePullSecrets:
      - name: regcred
      volumes:      
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-data-claim  


---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: dev
spec:
  selector:
    app: couchdb
  type: NodePort
  ports:
    - name: couchdb
      protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30084
