---

kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto
  namespace: mosquitto
data:
  mosquitto.conf: |
    allow_anonymous false
    password_file /mosquitto/config/passwordfile
    # Port to use for the default listener.
    port 1883
