apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homa-config
  namespace: homa
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
