---

kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homa
  labels:
    app: homeassistant
#    kubernetes.io/name: homeassistant
spec:
  type: NodePort
  ports:
    - name:
      port: 8123
      targetPort: 8123
      nodePort: 31823
  selector:
    app: homeassistant
