---

kind: Service
apiVersion: v1
metadata:
  name: coder
  namespace: dev
  labels:
    app: coder
spec:
  type: ClusterIP
  ports:
    - name:
      port: 7080
      targetPort: 7080
  selector:
    app: coder
