---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: opencv
  namespace: opencv
  labels:
    app: opencv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencv
  template:
    metadata:
      labels:
        app: opencv
    spec:
      volumes:
        - name: dataset-volume
          nfs:
            server: 10.0.0.29
            path: /export/kube-storage/opencv/dataset
        - name: encodings-volume
          nfs:
            server: 10.0.0.29
            path: /export/kube-storage/opencv/encodings
      containers:
        - name: opencv
          image: 'avishayil/opencv-video-analysis:latest'
          resources:
            limits:
              cpu: 400m
              memory: 500Mi
          volumeMounts:
            - name: dataset-volume
              mountPath: /data/dataset
            - name: encodings-volume
              mountPath: /data/encodings
          env:
            - name: LOGLEVEL
              value: "INFO"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
