---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-volume
          nfs:
            server: 10.0.0.29
            path: /export/kube-storage/mysql
      containers:
        - name: mysql
          image: 'hypriot/rpi-mysql:latest'
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
          envFrom:
            - secretRef:
                name: mysql
      restartPolicy: Always
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
