---

kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    kubernetes.io/name: mysql
spec:
  ports:
    - name: dns
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30889
  selector:
    app: mysql
  type: NodePort
