apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-al-config
  namespace: vpn
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
