apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-volume
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
