---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: coder
  namespace: dev
  labels:
    app: coder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder
  template:
    metadata:
      labels:
        app: coder
    spec:
      containers:
        - name: coder
          image: 'ghcr.io/coder/coder:latest'
          ports:
            - containerPort: 8123
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
          - name: CODER_HTTP_ADDRESS
            value: '0.0.0.0:7080'
          - name: CODER_ACCESS_URL
            value: 'http://code.meba.xyz'
      restartPolicy: Always
      nodeName: vps-e750b1ad 
