---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: wg-al
  namespace: wireguard
  labels:
    app: wg-al
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-al
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wg-al
    spec:
      containers:
        - name: wg-al
          image: 'lscr.io/linuxserver/wireguard:latest'
          env:
          - name: SERVERURL
            value: "vpn.meba.xyz"
          - name: SERVERPORT
            value: "40454"
          - name: PEERS
            value: "p30,rpimx,freebox,elenaTab,elenaPhone"
          - name: PEERDNS
            value: "auto"
          - name: INTERNAL_SUBNET
            value: "192.168.101.0"
          - name: ALLOWEDIPS
            value: "0.0.0.0/0"
          - name: LOG_CONFS
            value: "true"
          ports:
          - containerPort: 51820
            protocol: UDP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - name: wg-al-volume
            mountPath: /config
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: wg-al-volume
        persistentVolumeClaim:
          claimName: wg-al-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      nodeSelector:
        zone: alsace
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
