---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpimxssh
  namespace: tunnel
  labels:
    app: rpimxssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpimxssh
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rpimxssh
    spec:
      containers:
        - name: rpimxssh
          image: 'linuxserver/openssh-server'
          env:
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-public-key
                key: mebarpimx
          ports:
            - containerPort: 2222
              protocol: TCP
          #resources:
          #  limits:
          #    cpu: 100m
          #    memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: rpimxwg
  namespace: tunnel
  labels:
    app: rpimxwg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpimxwg
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rpimxwg
    spec:
      containers:
        - name: rpimxwg
          image: 'linuxserver/openssh-server'
          env:
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: ssh-public-key
                key: mebarpimx
          ports:
            - containerPort: 2222
              protocol: TCP
          #resources:
          #  limits:
          #    cpu: 100m
          #    memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
