apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: registry
type: Opaque
data:
  HTPASSWD: YWRtaW46JDJ5JDA1JE0wMjVoZ284MmZOTWNMNUtxLlVJT09vR045UXo1d3ZUWDR1R1VEZVNjRjM5WjZpazlmZ1B5Cgo=
