apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homa-config
  namespace: homeassistant
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
