---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  namespace: homa
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homeassistant

    spec:
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: homa-config
      nodeSelector:
        "kubernetes.io/zone": roche
      containers:
        - name: homeassistant
          image: 'homeassistant/home-assistant:latest'
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config-volume
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: false
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
