apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-config
  namespace: site2site
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi
