---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: wireguard
  namespace: site2site
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wireguard
    spec:
      containers:
        - name: wg-mx
          image: 'lscr.io/linuxserver/wireguard:latest'
          env:
          #- name: PUID
          #  value: "0"
          #- name: PGID
          #  value: "0"
          - name: SERVERURL
            value: "ps00.strasbourg.meba.xyz"
          - name: SERVERPORT
            value: "31821"
          - name: PEERS
            value: "hs,mx,al"
          - name: PEERDNS
            value: "auto"
          - name: INTERNAL_SUBNET
            value: "10.44.22.0"
          - name: ALLOWEDIPS
            value: "0.0.0.0"
          - name: LOG_CONFS
            value: "false"
          ports:
            - containerPort: 51820
              protocol: UDP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - name: wg-config
            mountPath: /config
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: wg-config
        persistentVolumeClaim:
          claimName: wg-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
