---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  template:
    metadata:
      name: cloudflare
      namespace: cloudflare
  encryptedData:
    API_KEY: AgBq/ohHTx7xefD9e+oMQid4mAS3VDMxeSk2vSPuYCdgjzxzcJOp5LU4+quP8Z5Nw7jHXnK3jtBiCgrq04lkox0mM70b+v6MfnwXPXk7Fu30I13cox1yUT8bfq8K8lQ7XFz+ZIxDkVCLrTJVI/urtmK1r62EXM+6oaJw24qhGZi1K8fLEPu+GnvOMzfOMc/poroOx4quiP9EQcdurmumqYrfGJ2YMdxbafonXdR1x/qetAa9P0Ant7X7FSprtUsbIujXgtNPl5rYsNdmKx07W5cJZyJfiy4k9XVST6UbqyZxHH37+GOnGrPFRJw63rShfVXZXmY67nf7TsyGbcHjUYCgElLb2RpoB1oTANXCTvY9FCRU/fUoPKHd5qZRYWlsPOJT8eAaLx+XUJnlka9b2DZgeRWpL5LyaKWDN2K7t/CLk2yrIBJ6Kr2IuP4ZhhGoJr6Lacck/+rEFZ4VtszNvvo5kXV1vblpy0d6qiqjU00TtkV7f4VMBI2OV+2hHZMub2DUia1zLNELq2qB/3yGo8esSMUzyGRbYqHf2JOBvvvX1af8p45uwQd/LpEoMPbIgdB6rcZTII+7VkmcDWdFGkv5gJ6lNy9yljycLZeM99l887+UhubarYuE0zt0B6uz/Ogqpj+Mu660upUK8O3RROUKOupPFpcpthYTwBXSGzpytcS9s5ah/L5P1LzpnpFADauSo4SWGcvRod0GXAM6qPQm8MvAHU/JFRqT5cVDXfkMA9+QEFU5EhX2sA==
